import type { Metadata } from "next";
// import localFont from "next/font/local";
// import  RotatingLoader  from "./components/Loader/Loader";
import "./globals.css";
import { RotatingLoader } from "./components/Loader/NewLoader";
import Loading from "./Loading";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
import { DataProvider } from "./contexts/UseDataContext";
import { Suspense } from "react";

// const { RotatingLoader } = Loader()
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DataProvider>{children}</DataProvider>
      </body>
    </html>
  );
}
